### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by MisaLiu** [WankkoRee/eaio#11]
1. 如果被链接的 Electron 程序的开发者发布了包含 Electron 更新的包，那么已经被链接的文件是否会受到影响？
2. 为何不将 Electron 内核统一放置在一个盘符下，而是选择在每一个盘符下放置 Electron 内核，即使其他盘符下已经有相同版本的内核？

**Comment by WankkoRee** [comment]
第一个问题分两种情况，如果是覆写文件进行更新的话（概率很小），会造成其他链接到同个版本的应用也被更新，这个时候需要先断开此应用的链接，然后重新下载先前的 Electron 到链接仓库（此时其他链接到同个版本的应用会自动重新链接回原样），再将此应用重新链接即可；如果是覆盖文件进行更新的话，重新连接即可。

----

第二个问题，主要是硬链接这个模式决定的，必须要被链接的文件和链接的文件都在同个磁盘下才能生效。

**Comment by MisaLiu** [comment]
好的，了解了
